
--User 테이블 생성
drop table if exists USER CASCADE;
create table USER
(
    id bigint generated by default as identity, -- Auto Increment
    name varchar(255),
    type bigint,

    reg_date bigint,
    updt_date bigint,

    primary key (id)
);
-- create item table
drop table if exists ITEM CASCADE;
create table ITEM
(
    id bigint generated by default as identity, -- Auto Increment
    name_kor varchar(255),
    name_eng varchar(255),
    name_chn varchar(255),

    text_kor varchar(255),
    text_eng varchar(255),
    text_chn varchar(255),

    creator varchar(255),
    editor varchar(255),

    price double,
    commission double,
    approved bigint,

    reg_date date,
    updt_date date,

    primary key (id)
);


--ExchangeRate
--drop table if exists EXCHANGE_RATE CASCADE;
create table EXCHANGE_RATE
(

    country varchar(255),
    rate double,

    reg_date date,
    updt_date date,

    primary key (country)
);

--drop table if exists PURCHASED_LIST CASCADE;
create table PURCHASED_LIST
(
    id bigint generated by default as identity, -- Auto Increment

    item_id bigint,
    customer_id varchar(255),
    quantity bigint,
    price double,
    totalprice double,
    currency varchar(255)

    reg_date date,
    updt_date date,

    primary key (id)
);


--